I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script/2_Lvl/L2/lvl2.rpy", line 298, in script
    $ c = c+1
  File "game/script/2_Lvl/L2/lvl2.rpy", line 298, in <module>
    $ c = c+1
NameError: name 'c' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script/2_Lvl/L2/lvl2.rpy", line 298, in script
    $ c = c+1
  File "D:\Game Development\renpy-8.2.1-sdk\renpy\ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Game Development\renpy-8.2.1-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script/2_Lvl/L2/lvl2.rpy", line 298, in <module>
    $ c = c+1
NameError: name 'c' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.1.24030407
Rights Quest 1 1.0
Tue May  7 01:02:09 2024
